### PR TITLE
Update Notification

### PR DESCRIPTION
**Pull request by Maan-Sharma**
Now its not gonna crash ,if PERMISSION is not given

### CODE REVIEW

**Comment by ashut0sh75** [comment]
Well it did not crash just notifications were not generated.

**Comment by ashut0sh75** [comment]
@Maan-Sharma We think we should ask for all the permission from the user to resolve this like all app do and also  do not remove the toast.

**Comment by vinitfreakk** [comment]
well the app is not asking notification permission in android 11 and the notification are working. Where as in android 13 the notification permission is not asked you have to manaully allow it from settings.  
because of which in android 13 even after saving image to gallery it shows toast saying "no image selected".
this is because in Android 11 and lower, apps are automatically granted notification permission when they are installed. However, on Android 13 and higher, apps must request notification permission from the user before they can send notifications

**Comment by ashut0sh75** [comment]
Yes that is why we have decided to ask for all permission after install to resolve this issue. Thank you @vinitfreakk for making it more clear.

**Comment by vinitfreakk** [comment]
If you can assign this, I can try to fix it

**Comment by ashut0sh75** [comment]
@vinitfreakk you can create a new issue for that as this PR is of @Maan-Sharma.

**Comment by vinitfreakk** [comment]
@ashut0sh75 yeah i have done it

**Comment by ashut0sh75** [comment]
We have a better fix now so we are merging another PR for this.

**Pull request closed without merging**
